### ISSUE TITLE
ErrorInterceptors

### ISSUE THREAD

**Issue by zeroows** [bennadel/httpi#4]
Dear, 

If you could add an ErrorInterceptor to httpi.

It may look like this:

```
var resource = httpi.resource( "api/friends/( :listCommand | :id/:itemCommand )" );

        // Clear list of friends - matching listCommand.
        var promise = resource.post({
            data: {
                listCommand: "reset"
            }
        })
        .setErrorInterceptor(function(response, deferred, responseHandler) {
            if(response.status === 403) {

                return false; 
            }else if(response.status === 404) {

                return false;
            }

            return true;
        });
```

**Comment by aljopro** [comment]
Zeroows,
  you could also use an http Interceptor. This would allow you to capture those types of status and reject the request for yourself.  
https://docs.angularjs.org/api/ng/service/$http#interceptors

If you feel you need this Error Interceptor functionality. Might I suggest a decorator service to wrap httpi.
http://stackoverflow.com/questions/16075982/angularjs-what-are-decorators-and-how-are-they-used
